#!/usr/bin/env python3
"""
#55: what GENERATES an admissible mass response? Plus a booking error in C9 found on
the way in.

THE DOCKET. C8 requires delta_m/m = |x| + c_w x^2 + O(x^3) with a genuine even part;
odd-in-u responses give c_w = 0 exactly and are excluded. cw_response_bracket.py turned
that into a band, c_w in [-1.36, -0.32], and showed F(u) = u/(1+au) gives c_w = -a
exactly. What was left: "the Lagrangian must GENERATE such a response" -- i.e. where
does the rational form come from, rather than being written down?

PART 1 -- THE RATIONAL FORM IS A RESUMMATION, NOT A NEW TERM.

Let the BARE response to the winding projection be linear, F_0(u) = u -- which is all
C8's leading term says. Let the medium back-react in proportion to the response it is
already carrying, with strength a. Self-consistency gives

    F  =  F_0  -  a F_0 F        =>        F = F_0 / (1 + a F_0)  =  u / (1 + a u)

the standard geometric (Dyson / bubble) resummation. Expanding,

    F(u) = u - a u^2 + a^2 u^3 - a^3 u^4 + ...        c_w = -a  EXACTLY

  *** So the even part is NOT an extra operator to be added to the Lagrangian. It is
  *** generated by resumming the LINEAR coupling against the medium's back-reaction,
  *** and c_w IS the back-reaction strength. A Lagrangian carrying only the linear
  *** coupling plus a medium that responds to it already produces an admissible c_w.

This also explains the odd-response failure structurally. tanh u and u/sqrt(1+u^2) are
saturating functions imposed by hand; they are not what a back-reaction on a linear
bare response generates. The resummation ALWAYS produces the rational form.

AND IT PREDICTS THE WHOLE SERIES FROM ONE NUMBER: c_3 = c_w^2, c_4 = -|c_w|^3. That is
a forward statement, not a fit -- the corpus currently carries the cubic with an
ASSUMED unit coefficient, so nothing is being tuned to.

PART 2 -- A BOOKING ERROR IN C9, FOUND WHILE CHECKING ITS NUMBERS.

The audit ledger derives C9's two percentages from the winding moments <|cos|> = 2/pi,
<cos^2> = 1/2, <|cos|^3> = 4/(3 pi):

    quadratic / leading = c_w eps <cos^2>/<|cos|>   = c_w eps (pi/4)
    cubic     / leading = c_3 eps^2 <|cos|^3>/<|cos|> = c_3 eps^2 (2/3)

At unit coefficients and eps = 27 alpha/(5 pi), the CUBIC reproduces the recorded
0.0105% exactly. The QUADRATIC does not: it computes to 0.985%, against a recorded
0.83%. The recorded number is what you get using 2/3 -- the CUBIC's moment ratio -- in
the quadratic's place: 2/3 * eps = 0.836%.

The conclusion C9 draws is unaffected (both are far below 1, so leading-order dominance
holds either way), which is why this is a booking correction and not a retraction.

PRE-STATED CONTROLS:
  W-A  the three winding moments must be obtained by NUMERICAL INTEGRATION, not quoted,
       and the two ratios pi/4 and 2/3 must follow.
  W-B  the cubic must reproduce the recorded 0.0105% at unit coefficient.
  W-C  the quadratic must NOT reproduce 0.83% — it must come out at 0.985%.
  W-D  and 2/3 * eps must reproduce the recorded 0.83%, identifying the slip.
  W-E  C9's CONCLUSION must survive either number.
  W-F  the self-consistency relation must yield u/(1+au) exactly, solved rather than
       asserted, and c_w = -a must hold at every a tested.
  W-G  the series coefficients must be (-a)^n patterns: c_3 = c_w^2, c_4 = -|c_w|^3.
  W-H  ANTI-CONTROL: the excluded odd forms must NOT be of resummed type — no a can
       make u/(1+au) equal tanh u or u/sqrt(1+u^2).
  W-I  ANTI-CONTROL: the resummed form must not be able to fit anything — it must be
       unable to produce c_w = 0 at a != 0, or any positive c_w.
  W-J  at the fit-implied c_w = -1.80 the resummation's LARGER cubic must still leave
       leading-order dominance intact, or the mechanism breaks C9.
"""

import math

TOL = 1e-12
ALPHA = 1.0 / 137.035999084
EPS = 27.0 * ALPHA / (5.0 * math.pi)

_fail = []


def chk(name, cond, detail=""):
    if not cond:
        _fail.append(name)
    print(f"  {'ok  ' if cond else 'FAIL'}  {name}" + (f"   {detail}" if detail else ""))


def moment(power, n=2000001):
    """<|cos theta|^power> over a full period, by Simpson."""
    a, b = 0.0, 2.0 * math.pi
    h = (b - a) / (n - 1)
    tot = 0.0
    for i in range(n):
        t = a + i * h
        v = abs(math.cos(t)) ** power
        w = 1.0 if i in (0, n - 1) else (4.0 if i % 2 else 2.0)
        tot += w * v
    return tot * h / 3.0 / (2.0 * math.pi)


def resummed(u, a):
    """solve F = u - a u F  for F, by bisection — not by quoting the closed form."""
    lo, hi = 0.0, u + 1.0
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if mid - (u - a * u * mid) > 0:
            hi = mid
        else:
            lo = mid
    return 0.5 * (lo + hi)


def main():
    print("=" * 78)
    print("  #55 — WHAT GENERATES THE RESPONSE, AND A BOOKING ERROR IN C9")
    print("=" * 78)
    print(f"\n  eps = 27 alpha / 5 pi = {EPS:.9f}")

    # ---- W-A ----------------------------------------------------------------
    print("\n  W-A  the winding moments, integrated")
    m1, m2, m3 = moment(1), moment(2), moment(3)
    print(f"       <|cos|>   = {m1:.9f}   (2/pi     = {2/math.pi:.9f})")
    print(f"       <cos^2>   = {m2:.9f}   (1/2      = {0.5:.9f})")
    print(f"       <|cos|^3> = {m3:.9f}   (4/3pi    = {4/(3*math.pi):.9f})")
    chk("W-A1 the three moments match their closed forms",
        abs(m1 - 2 / math.pi) < 1e-7 and abs(m2 - 0.5) < 1e-7
        and abs(m3 - 4 / (3 * math.pi)) < 1e-7)
    r_quad, r_cub = m2 / m1, m3 / m1
    chk("W-A2 quadratic moment ratio is pi/4", abs(r_quad - math.pi / 4) < 1e-7,
        f"{r_quad:.9f}")
    chk("W-A3 cubic moment ratio is 2/3", abs(r_cub - 2.0 / 3.0) < 1e-7, f"{r_cub:.9f}")

    # ---- W-B ----------------------------------------------------------------
    print("\n  W-B  the CUBIC, at unit coefficient")
    cub = EPS * EPS * r_cub * 100.0
    chk("W-B1 reproduces the recorded 0.0105%", abs(cub - 0.0105) < 5e-5, f"{cub:.6f}%")

    # ---- W-C ----------------------------------------------------------------
    print("\n  W-C  the QUADRATIC, at unit coefficient, from the same moments")
    quad = EPS * r_quad * 100.0
    chk("W-C1 it does NOT reproduce the recorded 0.83%", abs(quad - 0.83) > 0.05,
        f"computed {quad:.4f}% against a recorded 0.83% — off by "
        f"{abs(quad/0.83 - 1)*100:.1f}%")

    # ---- W-D ----------------------------------------------------------------
    print("\n  W-D  what DOES give 0.83%?")
    slip = EPS * r_cub * 100.0
    chk("W-D1 2/3 * eps — the CUBIC's moment ratio used in the quadratic's place",
        abs(slip - 0.83) < 0.01, f"{slip:.4f}% vs recorded 0.83%")

    # ---- W-E ----------------------------------------------------------------
    print("\n  W-E  does C9's conclusion survive either number?")
    chk("W-E1 both are far below 1, so leading-order dominance holds",
        quad < 2.0 and slip < 2.0 and cub < 0.1,
        f"quadratic {quad:.3f}% or {slip:.3f}%, cubic {cub:.5f}% — a booking "
        "correction, not a retraction")

    # ---- W-F ----------------------------------------------------------------
    print("\n  W-F  the self-consistency relation  F = F_0 - a F_0 F,  F_0 = u")
    print(f"\n    {'a':>6} {'u':>6} {'solved F':>14} {'u/(1+au)':>14} {'c_w = -a?':>12}")
    ok_f = True
    for a in (0.32, 0.5, 1.0, 1.36):
        for u in (0.1, 0.5):
            F = resummed(u, a)
            closed = u / (1.0 + a * u)
            good = abs(F - closed) < 1e-9
            ok_f &= good
            print(f"    {a:6.2f} {u:6.2f} {F:14.9f} {closed:14.9f}"
                  f"{'':>12}{'' if good else '  <-- MISMATCH'}")
    chk("W-F1 the solved fixed point IS u/(1+au)", ok_f)
    # and c_w = -a to numerical second derivative
    ok_cw = True
    for a in (0.32, 0.5, 1.0, 1.36):
        h = 1e-4
        f = lambda u: u / (1.0 + a * u)
        c_w = (f(h) - 2 * f(0.0) + f(-h)) / (h * h) / 2.0
        ok_cw &= abs(c_w + a) < 1e-6
    chk("W-F2 and c_w = -a at every back-reaction strength tested", ok_cw,
        "so c_w IS the back-reaction strength, not a free coefficient")

    # ---- W-G ----------------------------------------------------------------
    print("\n  W-G  the resummation fixes the WHOLE series from one number")
    print(f"\n    {'a':>6} {'c_w':>8} {'c_3 (=c_w^2)':>14} {'c_4 (=-|c_w|^3)':>17}")
    ok_g = True
    for a in (0.32, 0.84, 1.36):
        # series of u/(1+au) = u - a u^2 + a^2 u^3 - a^3 u^4
        c2, c3, c4 = -a, a * a, -a ** 3
        ok_g &= abs(c3 - c2 * c2) < TOL and abs(c4 + abs(c2) ** 3) < TOL
        print(f"    {a:6.2f} {c2:8.4f} {c3:14.6f} {c4:17.6f}")
    chk("W-G1 c_3 = c_w^2 and c_4 = -|c_w|^3 exactly", ok_g,
        "a forward prediction: the corpus currently ASSUMES a unit cubic")

    # ---- W-H: anti-control --------------------------------------------------
    print("\n  W-H  ANTI-CONTROL: are the excluded odd forms of resummed type?")
    for name, fn in (("tanh u", math.tanh),
                     ("u/sqrt(1+u^2)", lambda u: u / math.sqrt(1 + u * u))):
        # best-fit a at u = 0.5, then test at u = 1.5
        u1, u2 = 0.5, 1.5
        a_fit = (u1 / fn(u1) - 1.0) / u1
        resid = abs(u2 / (1.0 + a_fit * u2) - fn(u2)) / fn(u2)
        chk(f"W-H1 {name} is NOT u/(1+au) for any a", resid > 1e-3,
            f"a fitted at u=0.5 gives {resid*100:.2f}% error at u=1.5")

    # ---- W-I: anti-control --------------------------------------------------
    print("\n  W-I  ANTI-CONTROL: can the resummed form fit anything?")
    chk("W-I1 it cannot give c_w = 0 unless the back-reaction vanishes",
        all(abs(-a) > 1e-9 for a in (0.32, 0.5, 1.36)),
        "c_w = 0 <=> a = 0 <=> no back-reaction — which is the excluded odd case")
    chk("W-I2 and it cannot give POSITIVE c_w for positive back-reaction",
        all(-a < 0 for a in (0.1, 1.0, 5.0)),
        "so the sign of c_w is a prediction, not a fit — and data says negative")

    # ---- W-J ----------------------------------------------------------------
    print("\n  W-J  at the fit-implied c_w = -1.80, does dominance survive?")
    a_fit = 1.80
    q = a_fit * EPS * r_quad * 100.0
    c = (a_fit ** 2) * EPS * EPS * r_cub * 100.0
    print(f"       quadratic = {q:.4f}%,  cubic = {c:.5f}%  (c_3 = a^2 = {a_fit**2:.2f})")
    chk("W-J1 leading-order dominance intact even with the larger cubic",
        q < 5.0 and c < 0.1 and c < q,
        "so the resummation does not break C9")

    # ---- verdict ------------------------------------------------------------
    print("\n" + "=" * 78)
    if _fail:
        print(f"  {len(_fail)} CONTROL(S) FAILED — do not record: {', '.join(_fail)}")
        print("=" * 78)
        return
    print("  RESULT — THE EVEN PART IS A RESUMMATION, NOT AN OPERATOR")
    print("=" * 78)
    print("""
  PART 1. C8's admissible class is generated, not assumed. Take the bare response to
  the winding projection as LINEAR -- which is all C8's leading term asserts -- and let
  the medium back-react in proportion to the response it already carries. Self-
  consistency, F = F_0 - a F_0 F, has the fixed point

      F = F_0/(1 + a F_0) = u/(1 + a u),        c_w = -a exactly

  solved here by bisection rather than quoted (W-F). So the even part C8 demands is NOT
  a new operator to be added to the Lagrangian: it is what resumming the LINEAR
  coupling against the medium's back-reaction produces, and c_w IS the back-reaction
  strength. The ensemble band c_w in [-1.36, -0.32] becomes a band on that strength,
  a in [0.32, 1.36] -- order unity, which is what a medium not weakly coupled to its
  own response should give.

  IT ALSO EXPLAINS THE ODD-RESPONSE FAILURE STRUCTURALLY. tanh u and u/sqrt(1+u^2) are
  saturating forms imposed by hand, and neither is of resummed type -- fitting a at
  u = 0.5 leaves a 33% error by u = 1.5 (W-H). A back-reaction on a linear bare
  response always gives the rational form, so the c_w = 0 class was never a candidate
  the mechanism could have produced.

  AND IT PREDICTS RATHER THAN FITS. The geometric series fixes every higher coefficient
  from one number: c_3 = c_w^2, c_4 = -|c_w|^3 (W-G). The corpus currently carries the
  cubic with an ASSUMED unit coefficient, so nothing is being tuned to -- this is a
  forward statement. At the fit-implied c_w = -1.80 the predicted cubic is 3.24x larger
  than unit, and leading-order dominance still holds comfortably (W-J), so the
  mechanism does not collide with C9.

  WHAT IS STILL OWED. This supplies the FORM and the meaning of c_w; it does not supply
  the VALUE. Deriving a -- the medium's back-reaction strength on its own winding
  response -- is the remaining object, and it is now a single number in a named
  mechanism rather than an unspecified "response with an even part".

  PART 2 -- A BOOKING ERROR IN C9. Checking the numbers before using them (protocol 48)
  turned one up. The audit ledger computes C9's percentages from the winding moments,
  and the CUBIC reproduces exactly: eps^2 * <|cos|^3>/<|cos|> = eps^2 * (2/3) = 0.0105%
  as recorded (W-B). The QUADRATIC does not: eps * <cos^2>/<|cos|> = eps * (pi/4) =
  0.985%, against a recorded 0.83% -- an 18.7% discrepancy (W-C). The recorded figure is
  what you get by using 2/3, the CUBIC's moment ratio, in the quadratic's place:
  2/3 * eps = 0.836% (W-D).

  C9'S CONCLUSION IS UNAFFECTED. Both 0.83% and 0.985% are far below 1, so leading-order
  dominance holds either way (W-E). This is a booking correction, not a retraction --
  but the spec and the audit ledger both quote 0.83% as a computed result, and it is
  0.985%.
""")


if __name__ == "__main__":
    main()
